### ISSUE TITLE
Output from i2spec4.exe has 1.0 as transmission for the entire range of wavenumbers 

### ISSUE THREAD

**Issue by SPrice310** [Lightning469/Forkey-Iodine-Cell-Code#2]
Hi Lighting469,

Thank you for posting this Forkey code! 

I am hoping that you can help me with my issue in running it. I downloaded MinGW to compile the i2line2.f and i2spec4.f files and then ran each executable (I get the same error messages as herrmanthegerman if i just try to execute the compiled .exe files). I saved the output of the first as testing.txt . I ran the second executable, i2spec4, and input my iodine cell's parameters (TEMP = 308.15 K, PRES = 0.696 torr, RLEN = 25.4 cm, WNSTART = 18793 cm^-1, WNSTOP = 18795 cm^-1, WNSTEP 0.0001 cm^-1) and then I entered testing.txt as the output file. I chose Type 1 since my range of wavenumbers isn't close to 18788 and I named this output file as testing_output.txt . I have tried varying the resolution chosen with higher and smaller increments.

Unfortunately, no matter what I do my testing_output.txt file just shows the transmission profile for the iodine for my wavenumber range to be 0.10000E+01 for every value of wavenumber. I am not sure where I am going wrong. I have the absorption profile for my iodine vapor cell at these conditions from the company that I purchased the cell from so I know how it should appear.

Do you have any suggestions? Thanks!

[testing.txt](https://github.com/Lightning469/Forkey-Iodine-Cell-Transmission-Code/files/4800210/testing.txt)

[testing_out.txt](https://github.com/Lightning469/Forkey-Iodine-Cell-Transmission-Code/files/4800212/testing_out.txt)

**Comment by Lightning469** [comment]
Hi SPrice310,

What is the intermediate file you are using for i2spec4.exe? The code should also ask you for one. If it's the one that's on the Github (18789-19791m2txt) then the name is a little misleading, because that one is missing values for 18790 & beyond (see ReadMe for details). Use i2line2.exe to generate these values, make sure that the intermediate file has values for the range you want.

Also, I'm not familiar with MinGW, I have been using CYGWIN with a gfortran compiler to run the Forkey codes & it works even for your desired properties, however any UNIX programming environment should do. Try doing it in CYGWIN as well if it still doesn't work on MinGW. You should not be getting any error messages either.

--

Here's my code spaghetti:

./i2spec4.exe
ENTER TEMPERATURE OF CELL [K]
308
ENTER PRESSURE OF CELL [TORR]
.696
ENTER LENGTH OF CELL [CM]
25.4
ENTER STARTING WAVENUMBER [CM-1]
18793
ENTER ENDING WAVENUMBER [CM-1]
18795
ENTER RESOLUTION [CM-1]
0.0001
ENTER NAME OF FILE WITH LINE DATA IN IT
18786-18800.txt (**generated using i2line2!**)
DO YOU WANT TO USE PUBLISHED VALUES FOR THE AVERAGE
ELECTRONIC TRANSITION STRENGTH, OR THE VALUE DETERMINED
EXPERIMENTALLY AT PRINCETON FOR DBLED ND:YAG?
TYPE 1 TO USE PUBLISHED VALUES (FOR ALL WAVENUMBERS OTHER THAN THOSE
           CLOSE TO 18788CM-1)
TYPE 2 TO USE PRINCETON VALUE (FOR FREQUENCY DOUBLED      ND:YAG I.E. CLOSE
           TO 18788CM-1)
1
WORKING ON  18794.0001 CM-1
ENTER OUTPUT DATA FILE NAME
test.txt
Note: The following floating-point exceptions are signalling: IEEE_UNDERFLOW_FLAG IEEE_DENORMAL

**Comment by SPrice310** [comment]
Hi Lightning469,

I downloaded Cygwin and the necessary packages for compiling Fortran files, ran the executables as instructed in the outlined procedure, and it worked like a charm. I have been able to achieve transmission spectra for several operating conditions. Thank you so much for the help!
